### ISSUE TITLE
TODO IPUCH next week

### ISSUE THREAD

**Issue by Ipuch** [Ipuch/spartacus-shoulder-kinematic-dataset#117]
- [x] First list of removed data from original list.
- [x] If case for uncomplete rotation dof data. Kijima
- [x] Remove charbonnier from the table. #26 #36 #127 
- [x] First draft of compliance function #25 #115
